const Sequelize = require('sequelize');

const sequelize = require('../../configs/connection');
const BedType = require('../../models/bed-type')(sequelize, Sequelize);
const AmenitiesType = require('../../models/amenities-type')(sequelize, Sequelize);
const AmenitiesIcon = require('../../models/amenities-icon')(sequelize, Sequelize);
const RoomStatus = require('../../models/room-status')(sequelize, Sequelize);
const Country = require('../../models/country')(sequelize, Sequelize);
const PropertyType = require('../../models/property-type')(sequelize, Sequelize);
const PropertyPurpose = require('../../models/property-purpose')(sequelize, Sequelize);
const PropertyLocation = require('../../models/property-location')(sequelize, Sequelize);
const PropertyLookingFor = require('../../models/property-looking-for')(sequelize, Sequelize);
const BookingStatus = require('../../models/booking-status')(sequelize, Sequelize);
BedType.sync();
AmenitiesType.sync();
AmenitiesIcon.sync();
RoomStatus.sync();
Country.sync();
PropertyType.sync();
PropertyPurpose.sync();
PropertyLocation.sync();
PropertyLookingFor.sync();
BookingStatus.sync();

exports.updateMaster = () => {
    BedType.findAll().then(bedType => {
        if (bedType.length == 0) { 
            BedType.bulkCreate([
                { name: 'Single bed', nameAr:'سرير مفرد'  },
                { name: 'Twin bed', nameAr:'سرير توأم'  },
                { name: 'King bed', nameAr:'سرير ملكي'  },
                { name: 'Triple bed', nameAr:'سرير ثلاثي' }
            ]);
        }
    });
    PropertyType.findAll().then(propertyType => {
        if (propertyType.length == 0) {
            PropertyType.bulkCreate([
                { name: 'Apartment', nameAr: 'شقة' }
            ]);
        }
    });
    BookingStatus.findAll().then(bookingStatus => {
        if (bookingStatus.length == 0) {
            BookingStatus.bulkCreate([
                { id:1, name: 'User Detail Pending', nameAr: 'تفاصيل المستخدم معلقة' },
                { id:2, name: 'Payment Pending', nameAr: 'انتظار الدفع' },
                { id:3, name: 'Completed', nameAr: 'منجز' },
                { id:4, name: 'Cancelled', nameAr: 'ألغيت' },
                { id:5, name: 'No Show', nameAr: 'لا يوجد عرض' },
                { id:6, name: 'Invalid', nameAr: 'غير صالحة' },
                { id:7, name: 'Checkout', nameAr: 'الدفع' },
            ]);
        }
    });
    PropertyLookingFor.findAll().then(propertyLookingFor => {
        if (propertyLookingFor.length == 0) {
            PropertyLookingFor.bulkCreate([
                { name: 'Residential', nameAr: 'سكني' }
            ]);
        }
    });
    PropertyLocation.findAll().then(propertyLocation => {
        if (propertyLocation.length == 0) {
            PropertyLocation.bulkCreate([
                { name: 'Bin Mahmoud', nameAr: 'بن محمود' },
                { name: 'Al Nasser', nameAr: 'الناصر' },
                { name: 'Al Sadd', nameAr: 'السد' },
                { name: 'Umm Ghuwailina', nameAr: 'ام غويلينه' },
                { name: 'Al Meera', nameAr: 'الميرة' },
                { name: 'Fareez Abdul Aziz', nameAr: 'فريز عبد العزيز' },
                { name: 'Garaffa', nameAr: 'جرؤأ' },
            ]);
        }
    });
    PropertyPurpose.findAll().then(propertyPurpose => {
        if (propertyPurpose.length == 0) {
            PropertyPurpose.bulkCreate([
                { name: 'Rent', nameAr: 'تأجير' }
            ]);
        }
    });
    AmenitiesType.findAll().then(amenitiesType => {
        if (amenitiesType.length == 0) {
            AmenitiesType.bulkCreate([
                { name: 'Room Amenities', nameAr: 'وسائل الراحة في الغرفة' },
                { name: 'Property Amenities', nameAr: 'وسائل الراحة في الممتلكات' },
            ]);
        }
    });
    RoomStatus.findAll().then(roomStatus => {
        if (roomStatus.length == 0) {
            RoomStatus.bulkCreate([
                { name: 'Available', nameAr: 'متاح' },
                { name: 'Reserved', nameAr: 'محجوز' }
            ]);
        }
    });
    Country.findAll().then(country => {
        if (country.length == 0) {
            Country.bulkCreate([
                { name: "Afghanistan", nameAr: "أفغانستان", alpha: "af", code: 93 },
                { name: "Albania", nameAr: "ألبانيا", alpha: "al", code: 355 },
                { name: "Algeria", nameAr: "الجزائر", alpha: "dz", code: 213 },
                { name: "American Samoa", nameAr: "ساموا الأمريكية", alpha: "as", code: 1684 },
                { name: "Andorra", nameAr: "أندورا", alpha: "ad", code: 376 },
                { name: "Angola", nameAr: "أنغولا", alpha: "ao", code: 244 },
                { name: "Anguilla", nameAr: "أنغيلا", alpha: "ai", code: 1264 },
                { name: "Antigua and Barbuda", nameAr: "أنتيغوا وبربودا", alpha: "ag", code: 1268 },
                { name: "Argentina", nameAr: "الأرجنتين", alpha: "ar", code: 54 },
                { name: "Armenia", nameAr: "أرمينيا", alpha: "am", code: 374 },
                { name: "Aruba", nameAr: "أروبا", alpha: "aw", code: 297 },
                { name: "Australia",nameAr: "أستراليا", alpha: "au", code: 61 },
                { name: "Austria", nameAr: "النمسا", alpha: "at", code: 43 },
                { name: "Azerbaijan", nameAr: "أذربيجان", alpha: "az", code: 994 },
                { name: "Bahamas",nameAr: "الباهاما", alpha: "bs", code: 1242 },
                { name: "Bahrain",nameAr: "البحرين", alpha: "bh", code: 973 },
                { name: "Bangladesh",nameAr: "بنغلاديش", alpha: "bd", code: 880 },
                { name: "Barbados",nameAr: "بربادوس", alpha: "bb", code: 1246 },
                { name: "Belarus",nameAr: "روسيا البيضاء", alpha: "by", code: 375 },
                { name: "Belgium",nameAr: "بلجيكا", alpha: "be", code: 32 },
                { name: "Belize",nameAr: "بليز", alpha: "bz", code: 501 },
                { name: "Benin",nameAr: "بنين", alpha: "bj", code: 229 },
                { name: "Bermuda",nameAr: "برمودا", alpha: "bm", code: 1441 },
                { name: "Bhutan",nameAr: "بوتان", alpha: "bt", code: 975 },
                { name: "Bolivia",nameAr: "بوليفيا", alpha: "bo", code: 591 },
                { name: "Bosnia and Herzegovina",nameAr: "البوسنة والهرسك", alpha: "ba", code: 387 },
                { name: "Botswana",nameAr: "بوتسوانا", alpha: "bw", code: 267 },
                { name: "Brazil",nameAr: "البرازيل", alpha: "br", code: 55 },
                { name: "Brunei Darussalam", nameAr: "بروناي دار السلام", alpha: "bn", code: 673 },
                { name: "Bulgaria",nameAr: "بلغاريا", alpha: "bg", code: 359 },
                { name: "Burkina Faso",nameAr: "بوركينا فاسو", alpha: "bf", code: 226 },
                { name: "Burundi",nameAr: "بوروندي", alpha: "bi", code: 257 },
                { name: "Cambodia",nameAr: "كمبوديا", alpha: "kh", code: 855 },
                { name: "Cameroon",nameAr: "الكاميرون", alpha: "cm", code: 237 },
                { name: "Canada",nameAr: "كندا", alpha: "ca", code: 1 },
                { name: "Cape Verde",nameAr: "الرأس الأخضر", alpha: "cv", code: 238 },
                { name: "Cayman Islands",nameAr: "جزر كايمان", alpha: "ky", code: 1345 },
                { name: "Central African Republic",nameAr: "جمهورية افريقيا الوسطى", alpha: "cf", code: 236 },
                { name: "Chad",nameAr: "تشاد", alpha: "td", code: 235 },
                { name: "Chile",nameAr: "تشيلي", alpha: "cl", code: 56 },
                { name: "China",nameAr: "الصين", alpha: "cn", code: 86 },
                { name: "Colombia",nameAr: "كولومبيا", alpha: "co", code: 57 },
                { name: "Comoros",nameAr: "جزر القمر", alpha: "km", code: 269 },
                { name: "Congo (DRC)",nameAr: "الكونغو (جمهورية الكونغو الديمقراطية)", alpha: "cd", code: 243 },
                { name: "Congo (Republic)",nameAr: "جمهورية الكونغو", alpha: "cg", code: 242 },
                { name: "Cook Islands",nameAr: "جزر كوك", alpha: "ck", code: 682 },
                { name: "Costa Rica",nameAr: "كوستاريكا", alpha: "cr", code: 506 },
                { name: "Ivory Coast",nameAr: "ساحل العاج", alpha: "ci", code: 225 },
                { name: "Croatia",nameAr: "كرواتيا", alpha: "hr", code: 385 },
                { name: "Cuba",nameAr: "كوبا", alpha: "cu", code: 53 },
                { name: "Cyprus",nameAr: "قبرص", alpha: "cy", code: 357 },
                { name: "Czech Republic",nameAr: "جمهورية التشيك", alpha: "cz", code: 420 },
                { name: "Denmark",nameAr: "الدنمارك", alpha: "dk", code: 45 },
                { name: "Djibouti",nameAr: "جيبوتي", alpha: "dj", code: 253 },
                { name: "Dominica",nameAr: "دومينيكا", alpha: "dm", code: 1767 },
                { name: "Dominican Republic",nameAr: "جمهورية الدومنيكان", alpha: "do", code: 1809 },
                { name: "Ecuador",nameAr: "الإكوادور", alpha: "ec", code: 593 },
                { name: "Egypt",nameAr: "مصر", alpha: "eg", code: 20 },
                { name: "El Salvador",nameAr: "السلفادور", alpha: "sv", code: 503 },
                { name: "Equatorial Guinea",nameAr: "غينيا الإستوائية", alpha: "gq", code: 240 },
                { name: "Eritrea",nameAr: "إريتريا", alpha: "er", code: 291 },
                { name: "Estonia",nameAr: "استونيا", alpha: "ee", code: 372 },
                { name: "Ethiopia",nameAr: "أثيوبيا", alpha: "et", code: 251 },
                { name: "Faroe Islands",nameAr: "جزر فاروس", alpha: "fo", code: 298 },
                { name: "Fiji",nameAr: "فيجي", alpha: "fj", code: 679 },
                { name: "Finland",nameAr: "فنلندا", alpha: "fi", code: 358 },
                { name: "France",nameAr: "فرنسا", alpha: "fr", code: 33 },
                { name: "French Polynesia",nameAr: "بولينيزيا الفرنسية", alpha: "pf", code: 689 },
                { name: "Gabon",nameAr: "الغابون", alpha: "ga", code: 241 },
                { name: "Gambia",nameAr: "غامبيا", alpha: "gm", code: 220 },
                { name: "Georgia",nameAr: "جورجيا", alpha: "ge", code: 995 },
                { name: "Germany",nameAr: "ألمانيا", alpha: "de", code: 49 },
                { name: "Ghana",nameAr: "غانا", alpha: "gh", code: 233 },
                { name: "Gibraltar",nameAr: "جبل طارق", alpha: "gi", code: 350 },
                { name: "Greece",nameAr: "اليونان", alpha: "gr", code: 30 },
                { name: "Greenland",nameAr: "الأرض الخضراء", alpha: "gl", code: 299 },
                { name: "Grenada",nameAr: "غرينادا", alpha: "gd", code: 1473 },
                { name: "Guadeloupe",nameAr: "جوادلوب", alpha: "gp", code: 590 },
                { name: "Guam",nameAr: "غوام", alpha: "gu", code: 1671 },
                { name: "Guatemala", nameAr: "غواتيمالا", alpha: "gt", code: 502 },
                { name: "Guernsey", nameAr: "غيرنسي", alpha: "gg", code: 44 },
                { name: "Guinea", nameAr: "غينيا", alpha: "gn", code: 224 },
                { name: "Guinea-Bissau", nameAr: "غينيا بيساو", alpha: "gw", code: 245 },
                { name: "Guyana", nameAr: "غيانا", alpha: "gy", code: 592 },
                { name: "Haiti", nameAr: "هايتي", alpha: "ht", code: 509 },
                { name: "Honduras", nameAr: "هندوراس", alpha: "hn", code: 504 },
                { name: "Hong Kong", nameAr: "هونج كونج", alpha: "hk", code: 852 },
                { name: "Hungary", nameAr: "هنغاريا", alpha: "hu", code: 36 },
                { name: "Iceland", nameAr: "أيسلندا", alpha: "is", code: 354 },
                { name: "India", nameAr: "الهند", alpha: "in", code: 91 },
                { name: "Indonesia", nameAr: "أندونيسيا", alpha: "id", code: 62 },
                { name: "Iran", nameAr: "إيران", alpha: "ir", code: 98 },
                { name: "Iraq", nameAr: "العراق", alpha: "iq", code: 964 },
                { name: "Ireland", nameAr: "أيرلندا", alpha: "ie", code: 353 },
                { name: "Isle of Man", nameAr: "جزيرة آيل أوف مان", alpha: "im", code: 44 },
                { name: "Israel", nameAr: "إسرائيل", alpha: "il", code: 972 },
                { name: "Italy", nameAr: "إيطاليا", alpha: "it", code: 39 },
                { name: "Jamaica", nameAr: "جامايكا", alpha: "jm", code: 1876 },
                { name: "Japan", nameAr: "اليابان", alpha: "jp", code: 81 },
                { name: "Jersey", nameAr: "جيرسي", alpha: "je", code: 44 },
                { name: "Jordan", nameAr: "الأردن", alpha: "jo", code: 962 },
                { name: "Kazakhstan", nameAr: "كازاخستان", alpha: "kz", code: 7 },
                { name: "Kenya", nameAr: "كينيا", alpha: "ke", code: 254 },
                { name: "Kiribati", nameAr: "كيريباس", alpha: "ki", code: 686 },
                { name: "Kuwait", nameAr: "الكويت", alpha: "kw", code: 965 },
                { name: "Kyrgyzstan", nameAr: "قرغيزستان", alpha: "kg", code: 996 },
                { name: "Laos", nameAr: "لاوس", alpha: "la", code: 856 },
                { name: "Latvia", nameAr: "لاتفيا", alpha: "lv", code: 371 },
                { name: "Lebanon", nameAr: "لبنان", alpha: "lb", code: 961 },
                { name: "Lesotho", nameAr: "ليسوتو", alpha: "ls", code: 266 },
                { name: "Liberia", nameAr: "ليبيريا", alpha: "lr", code: 231 },
                { name: "Libya", nameAr: "ليبيا", alpha: "ly", code: 218 },
                { name: "Liechtenstein", nameAr: "ليختنشتاين", alpha: "li", code: 423 },
                { name: "Lithuania", nameAr: "ليتوانيا", alpha: "lt", code: 370 },
                { name: "Luxembourg", nameAr: "لوكسمبورغ", alpha: "lu", code: 352 },
                { name: "Macao", nameAr: "ماكاو", alpha: "mo", code: 853 },
                { name: "Macedonia", nameAr: "مقدونيا", alpha: "mk", code: 389 },
                { name: "Madagascar", nameAr: "مدغشقر", alpha: "mg", code: 261 },
                { name: "Malawi", nameAr: "مالاوي", alpha: "mw", code: 265 },
                { name: "Malaysia", nameAr: "ماليزيا", alpha: "my", code: 60 },
                { name: "Maldives", nameAr: "جزر المالديف", alpha: "mv", code: 960 },
                { name: "Mali", nameAr: "مالي", alpha: "ml", code: 223 },
                { name: "Malta", nameAr: "مالطا", alpha: "mt", code: 356 },
                { name: "Marshall Islands", nameAr: "جزر مارشال", alpha: "mh", code: 692 },
                { name: "Martinique", nameAr: "مارتينيك", alpha: "mq", code: 596 },
                { name: "Mauritania", nameAr: "موريتانيا", alpha: "mr", code: 222 },
                { name: "Mauritius", nameAr: "موريشيوس", alpha: "mu", code: 230 },
                { name: "Mexico", nameAr: "المكسيك", alpha: "mx", code: 52 },
                { name: "Micronesia", nameAr: "ميكرونيزيا", alpha: "fm", code: 691 },
                { name: "Moldova", nameAr: "مولدافيا", alpha: "md", code: 373 },
                { name: "Monaco", nameAr: "موناكو", alpha: "mc", code: 377 },
                { name: "Mongolia", nameAr: "منغوليا", alpha: "mn", code: 976 },
                { name: "Montenegro", nameAr: "الجبل الأسود", alpha: "me", code: 382 },
                { name: "Montserrat", nameAr: "مونتسيرات", alpha: "ms", code: 1664 },
                { name: "Morocco", nameAr: "المغرب", alpha: "ma", code: 212 },
                { name: "Mozambique", nameAr: "موزمبيق", alpha: "mz", code: 258 },
                { name: "Myanmar (Burma)", nameAr: "ميانمار (بورما)", alpha: "mm", code: 95 },
                { name: "Namibia", nameAr: "ناميبيا", alpha: "na", code: 264 },
                { name: "Nauru", nameAr: "ناورو", alpha: "nr", code: 674 },
                { name: "Nepal", nameAr: "نيبال", alpha: "np", code: 977 },
                { name: "Netherlands", nameAr: "هولندا", alpha: "nl", code: 31 },
                { name: "New Caledonia", nameAr: "كاليدونيا الجديدة", alpha: "nc", code: 687 },
                { name: "New Zealand", nameAr: "نيوزيلاندا", alpha: "nz", code: 64 },
                { name: "Nicaragua", nameAr: "نيكاراغوا", alpha: "ni", code: 505 },
                { name: "Niger", nameAr: "النيجر", alpha: "ne", code: 227 },
                { name: "Nigeria", nameAr: "نيجيريا", alpha: "ng", code: 234 },
                { name: "North Korea", nameAr: "كوريا الشماليه", alpha: "kp", code: 850 },
                { name: "Norway", nameAr: "النرويج", alpha: "no", code: 47 },
                { name: "Oman", nameAr: "عمان", alpha: "om", code: 968 },
                { name: "Pakistan", nameAr: "باكستان", alpha: "pk", code: 92 },
                { name: "Palau", nameAr: "بالاو", alpha: "pw", code: 680 },
                { name: "Palestinian Territory", nameAr: "الأراضي الفلسطينية", alpha: "ps", code: 970 },
                { name: "Panama", nameAr: "بناما", alpha: "pa", code: 507 },
                { name: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة", alpha: "pg", code: 675 },
                { name: "Paraguay", nameAr: "باراغواي", alpha: "py", code: 595 },
                { name: "Peru", nameAr: "بيرو", alpha: "pe", code: 51 },
                { name: "Philippines", nameAr: "الفلبين", alpha: "ph", code: 63 },
                { name: "Poland", nameAr: "بولندا", alpha: "pl", code: 48 },
                { name: "Portugal", nameAr: "البرتغال", alpha: "pt", code: 351 },
                { name: "Puerto Rico", nameAr: "بورتوريكو", alpha: "pr", code: 1787 },
                { name: "Qatar", nameAr: "دولة قطر", alpha: "qa", code: 974 },
                { name: "Reunion", nameAr: "جمع شمل", alpha: "re", code: 262 },
                { name: "Romania", nameAr: "رومانيا", alpha: "ro", code: 40 },
                { name: "Russian Federation", nameAr: "الاتحاد الروسي", alpha: "ru", code: 7 },
                { name: "Rwanda", nameAr: "رواندا", alpha: "rw", code: 250 },
                { name: "Saint Kitts and Nevis", nameAr: "سانت كيتس ونيفيس", alpha: "kn", code: 1869 },
                { name: "Saint Lucia", nameAr: "سانت لوسيا", alpha: "lc", code: 1758 },
                { name: "Saint Vincent and the Grenadines", nameAr: "سانت فنسنت وجزر غرينادين", alpha: "vc", code: 1784 },
                { name: "Samoa", nameAr: "ساموا", alpha: "ws", code: 685 },
                { name: "San Marino", nameAr: "سان مارينو", alpha: "sm", code: 378 },
                { name: "Sao Tome and Principe", nameAr: "ساو تومي وبرينسيبي", alpha: "st", code: 239 },
                { name: "Saudi Arabia", nameAr: "المملكة العربية السعودية", alpha: "sa", code: 966 },
                { name: "Senegal", nameAr: "السنغال", alpha: "sn", code: 221 },
                { name: "Serbia", nameAr: "صربيا", alpha: "rs", code: 381 },
                { name: "Seychelles", nameAr: "سيشيل", alpha: "sc", code: 248 },
                { name: "Sierra Leone", nameAr: "سيراليون", alpha: "sl", code: 232 },
                { name: "Singapore", nameAr: "سنغافورة", alpha: "sg", code: 65 },
                { name: "Slovakia", nameAr: "سلوفاكيا", alpha: "sk", code: 421 },
                { name: "Slovenia", nameAr: "سلوفينيا", alpha: "si", code: 386 },
                { name: "Solomon Islands", nameAr: "جزر سليمان", alpha: "sb", code: 677 },
                { name: "Somalia", nameAr: "الصومال", alpha: "so", code: 252 },
                { name: "South Africa", nameAr: "جنوب أفريقيا", alpha: "za", code: 27 },
                { name: "South Korea", nameAr: "كوريا الجنوبية", alpha: "kr", code: 82 },
                { name: "Spain", nameAr: "إسبانيا", alpha: "es", code: 34 },
                { name: "Sri Lanka", nameAr: "سيريلانكا", alpha: "lk", code: 94 },
                { name: "Sudan", nameAr: "السودان", alpha: "sd", code: 249 },
                { name: "Suriname", nameAr: "سورينام", alpha: "sr", code: 597 },
                { name: "Swaziland", nameAr: "سوازيلاند", alpha: "sz", code: 268 },
                { name: "Sweden", nameAr: "السويد", alpha: "se", code: 46 },
                { name: "Switzerland", nameAr: "سويسرا", alpha: "ch", code: 41 },
                { name: "Syrian Arab Republic", nameAr: "الجمهورية العربية السورية", alpha: "sy", code: 963 },
                { name: "Taiwan, Province of China", nameAr: "مقاطعة تايوان الصينية", alpha: "tw", code: 886 },
                { name: "Tajikistan", nameAr: "طاجيكستان", alpha: "tj", code: 992 },
                { name: "Tanzania", nameAr: "تنزانيا", alpha: "tz", code: 255 },
                { name: "Thailand", nameAr: "تايلاند", alpha: "th", code: 66 },
                { name: "Timor-Leste", nameAr: "تيمور الشرقية", alpha: "tl", code: 670 },
                { name: "Togo", nameAr: "توجو", alpha: "tg", code: 228 },
                { name: "Tonga", nameAr: "تونغا", alpha: "to", code: 676 },
                { name: "Trinidad and Tobago", nameAr: "ترينداد وتوباغو", alpha: "tt", code: 1868 },
                { name: "Tunisia", nameAr: "تونس", alpha: "tn", code: 216 },
                { name: "Turkey", nameAr: "ديك رومي", alpha: "tr", code: 90 },
                { name: "Turkmenistan", nameAr: "تركمانستان", alpha: "tm", code: 993 },
                { name: "Turks and Caicos Islands", nameAr: "جزر تركس وكايكوس", alpha: "tc", code: 1649 },
                { name: "Tuvalu", nameAr: "توفالو", alpha: "tv", code: 688 },
                { name: "Uganda", nameAr: "أوغندا", alpha: "ug", code: 256 },
                { name: "Ukraine", nameAr: "أوكرانيا", alpha: "ua", code: 380 },
                { name: "United Arab Emirates", nameAr: "الإمارات العربية المتحدة", alpha: "ae", code: 971 },
                { name: "United Kingdom", nameAr: "المملكة المتحدة", alpha: "gb", code: 44 },
                { name: "United States", nameAr: "الولايات المتحدة الأمريكية", alpha: "us", code: 1 },
                { name: "Uruguay", nameAr: "أوروغواي", alpha: "uy", code: 598 },
                { name: "Uzbekistan", nameAr: "أوزبكستان", alpha: "uz", code: 998 },
                { name: "Vanuatu", nameAr: "فانواتو", alpha: "vu", code: 678 },
                { name: "Vatican City", nameAr: "مدينة الفاتيكان", alpha: "va", code: 379 },
                { name: "Venezuela", nameAr: "فنزويلا", alpha: "ve", code: 58 },
                { name: "Viet Nam", nameAr: "فييت نام", alpha: "vn", code: 84 },
                { name: "Virgin Islands (British)", nameAr: "جزر العذراء البريطانية)", alpha: "vg", code: 1284 },
                { name: "Virgin Islands (U.S.)", nameAr: "جزر فيرجن (الولايات المتحدة)", alpha: "vi", code: 1340 },
                { name: "Western Sahara", nameAr: "الصحراء الغربية", alpha: "eh", code: 212 },
                { name: "Yemen", nameAr: "اليمن", alpha: "ye", code: 967 },
                { name: "Zambia", nameAr: "زامبيا", alpha: "zm", code: 260 },
                { name: "Zimbabwe", nameAr: "زيمبابوي", alpha: "zw", code: 263 }
            ]);
        }
    });
    AmenitiesIcon.findAll().then(amenitiesIcon => {
        if (amenitiesIcon.length == 0) {
            AmenitiesIcon.bulkCreate([
                { name: "ad", value: "&#xf641;  ad" },
                { name: "address-book", value: "&#xf2b9;  address-book" },
                { name: "address-card", value: "&#xf2bb;  address-card" },
                { name: "adjust", value: "&#xf042;  adjust" },
                { name: "air-freshener", value: "&#xf5d0;  air-freshener" },
                { name: "align-center", value: "&#xf037;  align-center" },
                { name: "align-justify", value: "&#xf039;  align-justify" },
                { name: "align-left", value: "&#xf036;  align-left" },
                { name: "align-right", value: "&#xf038;  align-right" },
                { name: "allergies", value: "&#xf461;  allergies" },
                { name: "ambulance", value: "&#xf0f9;  ambulance" },
                { name: "american-sign-language-interpreting", value: "&#xf2a3;  american-sign-language-interpreting" },
                { name: "anchor", value: "&#xf13d;  anchor" },
                { name: "angle-double-down", value: "&#xf103;  angle-double-down" },
                { name: "angle-double-left", value: "&#xf100;  angle-double-left" },
                { name: "angle-double-right", value: "&#xf101;  angle-double-right" },
                { name: "angle-double-up", value: "&#xf102;  angle-double-up" },
                { name: "angle-down", value: "&#xf107;  angle-down" },
                { name: "angle-left", value: "&#xf104;  angle-left" },
                { name: "angle-right", value: "&#xf105;  angle-right" },
                { name: "angle-up", value: "&#xf106;  angle-up" },
                { name: "angry", value: "&#xf556;  angry" },
                { name: "ankh", value: "&#xf644;  ankh" },
                { name: "apple-alt", value: "&#xf5d1;  apple-alt" },
                { name: "archive", value: "&#xf187;  archive" },
                { name: "archway", value: "&#xf557;  archway" },
                { name: "arrow-alt-circle-down", value: "&#xf358;  arrow-alt-circle-down" },
                { name: "arrow-alt-circle-left", value: "&#xf359;  arrow-alt-circle-left" },
                { name: "arrow-alt-circle-right", value: "&#xf35a;  arrow-alt-circle-right" },
                { name: "arrow-alt-circle-up", value: "&#xf35b;  arrow-alt-circle-up" },
                { name: "arrow-circle-down", value: "&#xf0ab;  arrow-circle-down" },
                { name: "arrow-circle-left", value: "&#xf0a8;  arrow-circle-left" },
                { name: "arrow-circle-right", value: "&#xf0a9;  arrow-circle-right" },
                { name: "arrow-circle-up", value: "&#xf0aa;  arrow-circle-up" },
                { name: "arrow-down", value: "&#xf063;  arrow-down" },
                { name: "arrow-left", value: "&#xf060;  arrow-left" },
                { name: "arrow-right", value: "&#xf061;  arrow-right" },
                { name: "arrow-up", value: "&#xf062;  arrow-up" },
                { name: "arrows-alt", value: "&#xf0b2;  arrows-alt" },
                { name: "arrows-alt-h", value: "&#xf337;  arrows-alt-h" },
                { name: "arrows-alt-v", value: "&#xf338;  arrows-alt-v" },
                { name: "assistive-listening-systems", value: "&#xf2a2;  assistive-listening-systems" },
                { name: "asterisk", value: "&#xf069;  asterisk" },
                { name: "at", value: "&#xf1fa;  at" },
                { name: "atlas", value: "&#xf558;  atlas" },
                { name: "atom", value: "&#xf5d2;  atom" },
                { name: "audio-description", value: "&#xf29e;  audio-description" },
                { name: "award", value: "&#xf559;  award" },
                { name: "baby", value: "&#xf77c;  baby" },
                { name: "baby-carriage", value: "&#xf77d;  baby-carriage" },
                { name: "backspace", value: "&#xf55a;  backspace" },
                { name: "backward", value: "&#xf04a;  backward" },
                { name: "bacon", value: "&#xf7e5;  bacon" },
                { name: "balance-scale", value: "&#xf24e;  balance-scale" },
                { name: "balance-scale-left", value: "&#xf515;  balance-scale-left" },
                { name: "balance-scale-right", value: "&#xf516;  balance-scale-right" },
                { name: "ban", value: "&#xf05e;  ban" },
                { name: "band-aid", value: "&#xf462;  band-aid" },
                { name: "barcode", value: "&#xf02a;  barcode" },
                { name: "bars", value: "&#xf0c9;  bars" },
                { name: "baseball-ball", value: "&#xf433;  baseball-ball" },
                { name: "basketball-ball", value: "&#xf434;  basketball-ball" },
                { name: "bath", value: "&#xf2cd;  bath" },
                { name: "battery-empty", value: "&#xf244;  battery-empty" },
                { name: "battery-full", value: "&#xf240;  battery-full" },
                { name: "battery-half", value: "&#xf242;  battery-half" },
                { name: "battery-quarter", value: "&#xf243;  battery-quarter" },
                { name: "battery-three-quarters", value: "&#xf241;  battery-three-quarters" },
                { name: "bed", value: "&#xf236;  bed" },
                { name: "beer", value: "&#xf0fc;  beer" },
                { name: "bell", value: "&#xf0f3;  bell" },
                { name: "bell-slash", value: "&#xf1f6;  bell-slash" },
                { name: "bezier-curve", value: "&#xf55b;  bezier-curve" },
                { name: "bible", value: "&#xf647;  bible" },
                { name: "bicycle", value: "&#xf206;  bicycle" },
                { name: "biking", value: "&#xf84a;  biking" },
                { name: "binoculars", value: "&#xf1e5;  binoculars" },
                { name: "biohazard", value: "&#xf780;  biohazard" },
                { name: "birthday-cake", value: "&#xf1fd;  birthday-cake" },
                { name: "blender", value: "&#xf517;  blender" },
                { name: "blender-phone", value: "&#xf6b6;  blender-phone" },
                { name: "blind", value: "&#xf29d;  blind" },
                { name: "blog", value: "&#xf781;  blog" },
                { name: "bold", value: "&#xf032;  bold" },
                { name: "bolt", value: "&#xf0e7;  bolt" },
                { name: "bomb", value: "&#xf1e2;  bomb" },
                { name: "bone", value: "&#xf5d7;  bone" },
                { name: "bong", value: "&#xf55c;  bong" },
                { name: "book", value: "&#xf02d;  book" },
                { name: "book-dead", value: "&#xf6b7;  book-dead" },
                { name: "book-medical", value: "&#xf7e6;  book-medical" },
                { name: "book-open", value: "&#xf518;  book-open" },
                { name: "book-reader", value: "&#xf5da;  book-reader" },
                { name: "bookmark", value: "&#xf02e;  bookmark" },
                { name: "border-all", value: "&#xf84c;  border-all" },
                { name: "border-none", value: "&#xf850;  border-none" },
                { name: "border-style", value: "&#xf853;  border-style" },
                { name: "bowling-ball", value: "&#xf436;  bowling-ball" },
                { name: "box", value: "&#xf466;  box" },
                { name: "box-open", value: "&#xf49e;  box-open" },
                { name: "boxes", value: "&#xf468;  boxes" },
                { name: "braille", value: "&#xf2a1;  braille" },
                { name: "brain", value: "&#xf5dc;  brain" },
                { name: "bread-slice", value: "&#xf7ec;  bread-slice" },
                { name: "briefcase", value: "&#xf0b1;  briefcase" },
                { name: "briefcase-medical", value: "&#xf469;  briefcase-medical" },
                { name: "broadcast-tower", value: "&#xf519;  broadcast-tower" },
                { name: "broom", value: "&#xf51a;  broom" },
                { name: "brush", value: "&#xf55d;  brush" },
                { name: "bug", value: "&#xf188;  bug" },
                { name: "building", value: "&#xf1ad;  building" },
                { name: "bullhorn", value: "&#xf0a1;  bullhorn" },
                { name: "bullseye", value: "&#xf140;  bullseye" },
                { name: "burn", value: "&#xf46a;  burn" },
                { name: "bus", value: "&#xf207;  bus" },
                { name: "bus-alt", value: "&#xf55e;  bus-alt" },
                { name: "business-time", value: "&#xf64a;  business-time" },
                { name: "calculator", value: "&#xf1ec;  calculator" },
                { name: "calendar", value: "&#xf133;  calendar" },
                { name: "calendar-alt", value: "&#xf073;  calendar-alt" },
                { name: "calendar-check", value: "&#xf274;  calendar-check" },
                { name: "calendar-day", value: "&#xf783;  calendar-day" },
                { name: "calendar-minus", value: "&#xf272;  calendar-minus" },
                { name: "calendar-plus", value: "&#xf271;  calendar-plus" },
                { name: "calendar-times", value: "&#xf273;  calendar-times" },
                { name: "calendar-week", value: "&#xf784;  calendar-week" },
                { name: "camera", value: "&#xf030;  camera" },
                { name: "camera-retro", value: "&#xf083;  camera-retro" },
                { name: "campground", value: "&#xf6bb;  campground" },
                { name: "candy-cane", value: "&#xf786;  candy-cane" },
                { name: "cannabis", value: "&#xf55f;  cannabis" },
                { name: "capsules", value: "&#xf46b;  capsules" },
                { name: "car", value: "&#xf1b9;  car" },
                { name: "car-alt", value: "&#xf5de;  car-alt" },
                { name: "car-battery", value: "&#xf5df;  car-battery" },
                { name: "car-crash", value: "&#xf5e1;  car-crash" },
                { name: "car-side", value: "&#xf5e4;  car-side" },
                { name: "caret-down", value: "&#xf0d7;  caret-down" },
                { name: "caret-left", value: "&#xf0d9;  caret-left" },
                { name: "caret-right", value: "&#xf0da;  caret-right" },
                { name: "caret-square-down", value: "&#xf150;  caret-square-down" },
                { name: "caret-square-left", value: "&#xf191;  caret-square-left" },
                { name: "caret-square-right", value: "&#xf152;  caret-square-right" },
                { name: "caret-square-up", value: "&#xf151;  caret-square-up" },
                { name: "caret-up", value: "&#xf0d8;  caret-up" },
                { name: "carrot", value: "&#xf787;  carrot" },
                { name: "cart-arrow-down", value: "&#xf218;  cart-arrow-down" },
                { name: "cart-plus", value: "&#xf217;  cart-plus" },
                { name: "cash-register", value: "&#xf788;  cash-register" },
                { name: "cat", value: "&#xf6be;  cat" },
                { name: "certificate", value: "&#xf0a3;  certificate" },
                { name: "chair", value: "&#xf6c0;  chair" },
                { name: "chalkboard", value: "&#xf51b;  chalkboard" },
                { name: "chalkboard-teacher", value: "&#xf51c;  chalkboard-teacher" },
                { name: "charging-station", value: "&#xf5e7;  charging-station" },
                { name: "chart-area", value: "&#xf1fe;  chart-area" },
                { name: "chart-bar", value: "&#xf080;  chart-bar" },
                { name: "chart-line", value: "&#xf201;  chart-line" },
                { name: "chart-pie", value: "&#xf200;  chart-pie" },
                { name: "check", value: "&#xf00c;  check" },
                { name: "check-circle", value: "&#xf058;  check-circle" },
                { name: "check-double", value: "&#xf560;  check-double" },
                { name: "check-square", value: "&#xf14a;  check-square" },
                { name: "cheese", value: "&#xf7ef;  cheese" },
                { name: "chess", value: "&#xf439;  chess" },
                { name: "chess-bishop", value: "&#xf43a;  chess-bishop" },
                { name: "chess-board", value: "&#xf43c;  chess-board" },
                { name: "chess-king", value: "&#xf43f;  chess-king" },
                { name: "chess-knight", value: "&#xf441;  chess-knight" },
                { name: "chess-pawn", value: "&#xf443;  chess-pawn" },
                { name: "chess-queen", value: "&#xf445;  chess-queen" },
                { name: "chess-rook", value: "&#xf447;  chess-rook" },
                { name: "chevron-circle-down", value: "&#xf13a;  chevron-circle-down" },
                { name: "chevron-circle-left", value: "&#xf137;  chevron-circle-left" },
                { name: "chevron-circle-right", value: "&#xf138;  chevron-circle-right" },
                { name: "chevron-circle-up", value: "&#xf139;  chevron-circle-up" },
                { name: "chevron-down", value: "&#xf078;  chevron-down" },
                { name: "chevron-left", value: "&#xf053;  chevron-left" },
                { name: "chevron-right", value: "&#xf054;  chevron-right" },
                { name: "chevron-up", value: "&#xf077;  chevron-up" },
                { name: "child", value: "&#xf1ae;  child" },
                { name: "church", value: "&#xf51d;  church" },
                { name: "circle", value: "&#xf111;  circle" },
                { name: "circle-notch", value: "&#xf1ce;  circle-notch" },
                { name: "city", value: "&#xf64f;  city" },
                { name: "clinic-medical", value: "&#xf7f2;  clinic-medical" },
                { name: "clipboard", value: "&#xf328;  clipboard" },
                { name: "clipboard-check", value: "&#xf46c;  clipboard-check" },
                { name: "clipboard-list", value: "&#xf46d;  clipboard-list" },
                { name: "clock", value: "&#xf017;  clock" },
                { name: "clone", value: "&#xf24d;  clone" },
                { name: "closed-captioning", value: "&#xf20a;  closed-captioning" },
                { name: "cloud", value: "&#xf0c2;  cloud" },
                { name: "cloud-download-alt", value: "&#xf381;  cloud-download-alt" },
                { name: "cloud-meatball", value: "&#xf73b;  cloud-meatball" },
                { name: "cloud-moon", value: "&#xf6c3;  cloud-moon" },
                { name: "cloud-moon-rain", value: "&#xf73c;  cloud-moon-rain" },
                { name: "cloud-rain", value: "&#xf73d;  cloud-rain" },
                { name: "cloud-showers-heavy", value: "&#xf740;  cloud-showers-heavy" },
                { name: "cloud-sun", value: "&#xf6c4;  cloud-sun" },
                { name: "cloud-sun-rain", value: "&#xf743;  cloud-sun-rain" },
                { name: "cloud-upload-alt", value: "&#xf382;  cloud-upload-alt" },
                { name: "cocktail", value: "&#xf561;  cocktail" },
                { name: "code", value: "&#xf121;  code" },
                { name: "code-branch", value: "&#xf126;  code-branch" },
                { name: "coffee", value: "&#xf0f4;  coffee" },
                { name: "cog", value: "&#xf013;  cog" },
                { name: "cogs", value: "&#xf085;  cogs" },
                { name: "coins", value: "&#xf51e;  coins" },
                { name: "columns", value: "&#xf0db;  columns" },
                { name: "comment", value: "&#xf075;  comment" },
                { name: "comment-alt", value: "&#xf27a;  comment-alt" },
                { name: "comment-dollar", value: "&#xf651;  comment-dollar" },
                { name: "comment-dots", value: "&#xf4ad;  comment-dots" },
                { name: "comment-medical", value: "&#xf7f5;  comment-medical" },
                { name: "comment-slash", value: "&#xf4b3;  comment-slash" },
                { name: "comments", value: "&#xf086;  comments" },
                { name: "comments-dollar", value: "&#xf653;  comments-dollar" },
                { name: "compact-disc", value: "&#xf51f;  compact-disc" },
                { name: "compass", value: "&#xf14e;  compass" },
                { name: "compress", value: "&#xf066;  compress" },
                { name: "compress-arrows-alt", value: "&#xf78c;  compress-arrows-alt" },
                { name: "concierge-bell", value: "&#xf562;  concierge-bell" },
                { name: "cookie", value: "&#xf563;  cookie" },
                { name: "cookie-bite", value: "&#xf564;  cookie-bite" },
                { name: "copy", value: "&#xf0c5;  copy" },
                { name: "copyright", value: "&#xf1f9;  copyright" },
                { name: "couch", value: "&#xf4b8;  couch" },
                { name: "credit-card", value: "&#xf09d;  credit-card" },
                { name: "crop", value: "&#xf125;  crop" },
                { name: "crop-alt", value: "&#xf565;  crop-alt" },
                { name: "cross", value: "&#xf654;  cross" },
                { name: "crosshairs", value: "&#xf05b;  crosshairs" },
                { name: "crow", value: "&#xf520;  crow" },
                { name: "crown", value: "&#xf521;  crown" },
                { name: "crutch", value: "&#xf7f7;  crutch" },
                { name: "cube", value: "&#xf1b2;  cube" },
                { name: "cubes", value: "&#xf1b3;  cubes" },
                { name: "cut", value: "&#xf0c4;  cut" },
                { name: "database", value: "&#xf1c0;  database" },
                { name: "deaf", value: "&#xf2a4;  deaf" },
                { name: "democrat", value: "&#xf747;  democrat" },
                { name: "desktop", value: "&#xf108;  desktop" },
                { name: "dharmachakra", value: "&#xf655;  dharmachakra" },
                { name: "diagnoses", value: "&#xf470;  diagnoses" },
                { name: "dice", value: "&#xf522;  dice" },
                { name: "dice-d20", value: "&#xf6cf;  dice-d20" },
                { name: "dice-d6", value: "&#xf6d1;  dice-d6" },
                { name: "dice-five", value: "&#xf523;  dice-five" },
                { name: "dice-four", value: "&#xf524;  dice-four" },
                { name: "dice-one", value: "&#xf525;  dice-one" },
                { name: "dice-six", value: "&#xf526;  dice-six" },
                { name: "dice-three", value: "&#xf527;  dice-three" },
                { name: "dice-two", value: "&#xf528;  dice-two" },
                { name: "digital-tachograph", value: "&#xf566;  digital-tachograph" },
                { name: "directions", value: "&#xf5eb;  directions" },
                { name: "divide", value: "&#xf529;  divide" },
                { name: "dizzy", value: "&#xf567;  dizzy" },
                { name: "dna", value: "&#xf471;  dna" },
                { name: "dog", value: "&#xf6d3;  dog" },
                { name: "dollar-sign", value: "&#xf155;  dollar-sign" },
                { name: "dolly", value: "&#xf472;  dolly" },
                { name: "dolly-flatbed", value: "&#xf474;  dolly-flatbed" },
                { name: "donate", value: "&#xf4b9;  donate" },
                { name: "door-closed", value: "&#xf52a;  door-closed" },
                { name: "door-open", value: "&#xf52b;  door-open" },
                { name: "dot-circle", value: "&#xf192;  dot-circle" },
                { name: "dove", value: "&#xf4ba;  dove" },
                { name: "download", value: "&#xf019;  download" },
                { name: "drafting-compass", value: "&#xf568;  drafting-compass" },
                { name: "dragon", value: "&#xf6d5;  dragon" },
                { name: "draw-polygon", value: "&#xf5ee;  draw-polygon" },
                { name: "drum", value: "&#xf569;  drum" },
                { name: "drum-steelpan", value: "&#xf56a;  drum-steelpan" },
                { name: "drumstick-bite", value: "&#xf6d7;  drumstick-bite" },
                { name: "dumbbell", value: "&#xf44b;  dumbbell" },
                { name: "dumpster", value: "&#xf793;  dumpster" },
                { name: "dumpster-fire", value: "&#xf794;  dumpster-fire" },
                { name: "dungeon", value: "&#xf6d9;  dungeon" },
                { name: "edit", value: "&#xf044;  edit" },
                { name: "egg", value: "&#xf7fb;  egg" },
                { name: "eject", value: "&#xf052;  eject" },
                { name: "ellipsis-h", value: "&#xf141;  ellipsis-h" },
                { name: "ellipsis-v", value: "&#xf142;  ellipsis-v" },
                { name: "envelope", value: "&#xf0e0;  envelope" },
                { name: "envelope-open", value: "&#xf2b6;  envelope-open" },
                { name: "envelope-open-text", value: "&#xf658;  envelope-open-text" },
                { name: "envelope-square", value: "&#xf199;  envelope-square" },
                { name: "equals", value: "&#xf52c;  equals" },
                { name: "eraser", value: "&#xf12d;  eraser" },
                { name: "ethernet", value: "&#xf796;  ethernet" },
                { name: "euro-sign", value: "&#xf153;  euro-sign" },
                { name: "exchange-alt", value: "&#xf362;  exchange-alt" },
                { name: "exclamation", value: "&#xf12a;  exclamation" },
                { name: "exclamation-circle", value: "&#xf06a;  exclamation-circle" },
                { name: "exclamation-triangle", value: "&#xf071;  exclamation-triangle" },
                { name: "expand", value: "&#xf065;  expand" },
                { name: "expand-arrows-alt", value: "&#xf31e;  expand-arrows-alt" },
                { name: "external-link-alt", value: "&#xf35d;  external-link-alt" },
                { name: "external-link-square-alt", value: "&#xf360;  external-link-square-alt" },
                { name: "eye", value: "&#xf06e;  eye" },
                { name: "eye-dropper", value: "&#xf1fb;  eye-dropper" },
                { name: "eye-slash", value: "&#xf070;  eye-slash" },
                { name: "fan", value: "&#xf863;  fan" },
                { name: "fast-backward", value: "&#xf049;  fast-backward" },
                { name: "fast-forward", value: "&#xf050;  fast-forward" },
                { name: "fax", value: "&#xf1ac;  fax" },
                { name: "feather", value: "&#xf52d;  feather" },
                { name: "feather-alt", value: "&#xf56b;  feather-alt" },
                { name: "female", value: "&#xf182;  female" },
                { name: "fighter-jet", value: "&#xf0fb;  fighter-jet" },
                { name: "file", value: "&#xf15b;  file" },
                { name: "file-alt", value: "&#xf15c;  file-alt" },
                { name: "file-archive", value: "&#xf1c6;  file-archive" },
                { name: "file-audio", value: "&#xf1c7;  file-audio" },
                { name: "file-code", value: "&#xf1c9;  file-code" },
                { name: "file-contract", value: "&#xf56c;  file-contract" },
                { name: "file-csv", value: "&#xf6dd;  file-csv" },
                { name: "file-download", value: "&#xf56d;  file-download" },
                { name: "file-excel", value: "&#xf1c3;  file-excel" },
                { name: "file-export", value: "&#xf56e;  file-export" },
                { name: "file-image", value: "&#xf1c5;  file-image" },
                { name: "file-import", value: "&#xf56f;  file-import" },
                { name: "file-invoice", value: "&#xf570;  file-invoice" },
                { name: "file-invoice-dollar", value: "&#xf571;  file-invoice-dollar" },
                { name: "file-medical", value: "&#xf477;  file-medical" },
                { name: "file-medical-alt", value: "&#xf478;  file-medical-alt" },
                { name: "file-pdf", value: "&#xf1c1;  file-pdf" },
                { name: "file-powerpoint", value: "&#xf1c4;  file-powerpoint" },
                { name: "file-prescription", value: "&#xf572;  file-prescription" },
                { name: "file-signature", value: "&#xf573;  file-signature" },
                { name: "file-upload", value: "&#xf574;  file-upload" },
                { name: "file-video", value: "&#xf1c8;  file-video" },
                { name: "file-word", value: "&#xf1c2;  file-word" },
                { name: "fill", value: "&#xf575;  fill" },
                { name: "fill-drip", value: "&#xf576;  fill-drip" },
                { name: "film", value: "&#xf008;  film" },
                { name: "filter", value: "&#xf0b0;  filter" },
                { name: "fingerprint", value: "&#xf577;  fingerprint" },
                { name: "fire", value: "&#xf06d;  fire" },
                { name: "fire-alt", value: "&#xf7e4;  fire-alt" },
                { name: "fire-extinguisher", value: "&#xf134;  fire-extinguisher" },
                { name: "first-aid", value: "&#xf479;  first-aid" },
                { name: "fish", value: "&#xf578;  fish" },
                { name: "fist-raised", value: "&#xf6de;  fist-raised" },
                { name: "flag", value: "&#xf024;  flag" },
                { name: "flag-checkered", value: "&#xf11e;  flag-checkered" },
                { name: "flag-usa", value: "&#xf74d;  flag-usa" },
                { name: "flask", value: "&#xf0c3;  flask" },
                { name: "flushed", value: "&#xf579;  flushed" },
                { name: "folder", value: "&#xf07b;  folder" },
                { name: "folder-minus", value: "&#xf65d;  folder-minus" },
                { name: "folder-open", value: "&#xf07c;  folder-open" },
                { name: "folder-plus", value: "&#xf65e;  folder-plus" },
                { name: "font", value: "&#xf031;  font" },
                { name: "football-ball", value: "&#xf44e;  football-ball" },
                { name: "forward", value: "&#xf04e;  forward" },
                { name: "frog", value: "&#xf52e;  frog" },
                { name: "frown", value: "&#xf119;  frown" },
                { name: "frown-open", value: "&#xf57a;  frown-open" },
                { name: "funnel-dollar", value: "&#xf662;  funnel-dollar" },
                { name: "futbol", value: "&#xf1e3;  futbol" },
                { name: "gamepad", value: "&#xf11b;  gamepad" },
                { name: "gas-pump", value: "&#xf52f;  gas-pump" },
                { name: "gavel", value: "&#xf0e3;  gavel" },
                { name: "gem", value: "&#xf3a5;  gem" },
                { name: "genderless", value: "&#xf22d;  genderless" },
                { name: "ghost", value: "&#xf6e2;  ghost" },
                { name: "gift", value: "&#xf06b;  gift" },
                { name: "gifts", value: "&#xf79c;  gifts" },
                { name: "glass-cheers", value: "&#xf79f;  glass-cheers" },
                { name: "glass-martini", value: "&#xf000;  glass-martini" },
                { name: "glass-martini-alt", value: "&#xf57b;  glass-martini-alt" },
                { name: "glass-whiskey", value: "&#xf7a0;  glass-whiskey" },
                { name: "glasses", value: "&#xf530;  glasses" },
                { name: "globe", value: "&#xf0ac;  globe" },
                { name: "globe-africa", value: "&#xf57c;  globe-africa" },
                { name: "globe-americas", value: "&#xf57d;  globe-americas" },
                { name: "globe-asia", value: "&#xf57e;  globe-asia" },
                { name: "globe-europe", value: "&#xf7a2;  globe-europe" },
                { name: "golf-ball", value: "&#xf450;  golf-ball" },
                { name: "gopuram", value: "&#xf664;  gopuram" },
                { name: "graduation-cap", value: "&#xf19d;  graduation-cap" },
                { name: "greater-than", value: "&#xf531;  greater-than" },
                { name: "greater-than-equal", value: "&#xf532;  greater-than-equal" },
                { name: "grimace", value: "&#xf57f;  grimace" },
                { name: "grin", value: "&#xf580;  grin" },
                { name: "grin-alt", value: "&#xf581;  grin-alt" },
                { name: "grin-beam", value: "&#xf582;  grin-beam" },
                { name: "grin-beam-sweat", value: "&#xf583;  grin-beam-sweat" },
                { name: "grin-hearts", value: "&#xf584;  grin-hearts" },
                { name: "grin-squint", value: "&#xf585;  grin-squint" },
                { name: "grin-squint-tears", value: "&#xf586;  grin-squint-tears" },
                { name: "grin-stars", value: "&#xf587;  grin-stars" },
                { name: "grin-tears", value: "&#xf588;  grin-tears" },
                { name: "grin-tongue", value: "&#xf589;  grin-tongue" },
                { name: "grin-tongue-squint", value: "&#xf58a;  grin-tongue-squint" },
                { name: "grin-tongue-wink", value: "&#xf58b;  grin-tongue-wink" },
                { name: "grin-wink", value: "&#xf58c;  grin-wink" },
                { name: "grip-horizontal", value: "&#xf58d;  grip-horizontal" },
                { name: "grip-lines", value: "&#xf7a4;  grip-lines" },
                { name: "grip-lines-vertical", value: "&#xf7a5;  grip-lines-vertical" },
                { name: "grip-vertical", value: "&#xf58e;  grip-vertical" },
                { name: "guitar", value: "&#xf7a6;  guitar" },
                { name: "h-square", value: "&#xf0fd;  h-square" },
                { name: "hamburger", value: "&#xf805;  hamburger" },
                { name: "hammer", value: "&#xf6e3;  hammer" },
                { name: "hamsa", value: "&#xf665;  hamsa" },
                { name: "hand-holding", value: "&#xf4bd;  hand-holding" },
                { name: "hand-holding-heart", value: "&#xf4be;  hand-holding-heart" },
                { name: "hand-holding-usd", value: "&#xf4c0;  hand-holding-usd" },
                { name: "hand-lizard", value: "&#xf258;  hand-lizard" },
                { name: "hand-middle-finger", value: "&#xf806;  hand-middle-finger" },
                { name: "hand-paper", value: "&#xf256;  hand-paper" },
                { name: "hand-peace", value: "&#xf25b;  hand-peace" },
                { name: "hand-point-down", value: "&#xf0a7;  hand-point-down" },
                { name: "hand-point-left", value: "&#xf0a5;  hand-point-left" },
                { name: "hand-point-right", value: "&#xf0a4;  hand-point-right" },
                { name: "hand-point-up", value: "&#xf0a6;  hand-point-up" },
                { name: "hand-pointer", value: "&#xf25a;  hand-pointer" },
                { name: "hand-rock", value: "&#xf255;  hand-rock" },
                { name: "hand-scissors", value: "&#xf257;  hand-scissors" },
                { name: "hand-spock", value: "&#xf259;  hand-spock" },
                { name: "hands", value: "&#xf4c2;  hands" },
                { name: "hands-helping", value: "&#xf4c4;  hands-helping" },
                { name: "handshake", value: "&#xf2b5;  handshake" },
                { name: "hanukiah", value: "&#xf6e6;  hanukiah" },
                { name: "hard-hat", value: "&#xf807;  hard-hat" },
                { name: "hashtag", value: "&#xf292;  hashtag" },
                { name: "hat-cowboy", value: "&#xf8c0;  hat-cowboy" },
                { name: "hat-cowboy-side", value: "&#xf8c1;  hat-cowboy-side" },
                { name: "hat-wizard", value: "&#xf6e8;  hat-wizard" },
                { name: "haykal", value: "&#xf666;  haykal" },
                { name: "hdd", value: "&#xf0a0;  hdd" },
                { name: "heading", value: "&#xf1dc;  heading" },
                { name: "headphones", value: "&#xf025;  headphones" },
                { name: "headphones-alt", value: "&#xf58f;  headphones-alt" },
                { name: "headset", value: "&#xf590;  headset" },
                { name: "heart", value: "&#xf004;  heart" },
                { name: "heart-broken", value: "&#xf7a9;  heart-broken" },
                { name: "heartbeat", value: "&#xf21e;  heartbeat" },
                { name: "helicopter", value: "&#xf533;  helicopter" },
                { name: "highlighter", value: "&#xf591;  highlighter" },
                { name: "hiking", value: "&#xf6ec;  hiking" },
                { name: "hippo", value: "&#xf6ed;  hippo" },
                { name: "history", value: "&#xf1da;  history" },
                { name: "hockey-puck", value: "&#xf453;  hockey-puck" },
                { name: "holly-berry", value: "&#xf7aa;  holly-berry" },
                { name: "home", value: "&#xf015;  home" },
                { name: "horse", value: "&#xf6f0;  horse" },
                { name: "horse-head", value: "&#xf7ab;  horse-head" },
                { name: "hospital", value: "&#xf0f8;  hospital" },
                { name: "hospital-alt", value: "&#xf47d;  hospital-alt" },
                { name: "hospital-symbol", value: "&#xf47e;  hospital-symbol" },
                { name: "hot-tub", value: "&#xf593;  hot-tub" },
                { name: "hotdog", value: "&#xf80f;  hotdog" },
                { name: "hotel", value: "&#xf594;  hotel" },
                { name: "hourglass", value: "&#xf254;  hourglass" },
                { name: "hourglass-end", value: "&#xf253;  hourglass-end" },
                { name: "hourglass-half", value: "&#xf252;  hourglass-half" },
                { name: "hourglass-start", value: "&#xf251;  hourglass-start" },
                { name: "house-damage", value: "&#xf6f1;  house-damage" },
                { name: "hryvnia", value: "&#xf6f2;  hryvnia" },
                { name: "i-cursor", value: "&#xf246;  i-cursor" },
                { name: "ice-cream", value: "&#xf810;  ice-cream" },
                { name: "icicles", value: "&#xf7ad;  icicles" },
                { name: "icons", value: "&#xf86d;  icons" },
                { name: "id-badge", value: "&#xf2c1;  id-badge" },
                { name: "id-card", value: "&#xf2c2;  id-card" },
                { name: "id-card-alt", value: "&#xf47f;  id-card-alt" },
                { name: "igloo", value: "&#xf7ae;  igloo" },
                { name: "image", value: "&#xf03e;  image" },
                { name: "images", value: "&#xf302;  images" },
                { name: "inbox", value: "&#xf01c;  inbox" },
                { name: "indent", value: "&#xf03c;  indent" },
                { name: "industry", value: "&#xf275;  industry" },
                { name: "infinity", value: "&#xf534;  infinity" },
                { name: "info", value: "&#xf129;  info" },
                { name: "info-circle", value: "&#xf05a;  info-circle" },
                { name: "italic", value: "&#xf033;  italic" },
                { name: "jedi", value: "&#xf669;  jedi" },
                { name: "joint", value: "&#xf595;  joint" },
                { name: "journal-whills", value: "&#xf66a;  journal-whills" },
                { name: "kaaba", value: "&#xf66b;  kaaba" },
                { name: "key", value: "&#xf084;  key" },
                { name: "keyboard", value: "&#xf11c;  keyboard" },
                { name: "khanda", value: "&#xf66d;  khanda" },
                { name: "kiss", value: "&#xf596;  kiss" },
                { name: "kiss-beam", value: "&#xf597;  kiss-beam" },
                { name: "kiss-wink-heart", value: "&#xf598;  kiss-wink-heart" },
                { name: "kiwi-bird", value: "&#xf535;  kiwi-bird" },
                { name: "landmark", value: "&#xf66f;  landmark" },
                { name: "language", value: "&#xf1ab;  language" },
                { name: "laptop", value: "&#xf109;  laptop" },
                { name: "laptop-code", value: "&#xf5fc;  laptop-code" },
                { name: "laptop-medical", value: "&#xf812;  laptop-medical" },
                { name: "laugh", value: "&#xf599;  laugh" },
                { name: "laugh-beam", value: "&#xf59a;  laugh-beam" },
                { name: "laugh-squint", value: "&#xf59b;  laugh-squint" },
                { name: "laugh-wink", value: "&#xf59c;  laugh-wink" },
                { name: "layer-group", value: "&#xf5fd;  layer-group" },
                { name: "leaf", value: "&#xf06c;  leaf" },
                { name: "lemon", value: "&#xf094;  lemon" },
                { name: "less-than", value: "&#xf536;  less-than" },
                { name: "less-than-equal", value: "&#xf537;  less-than-equal" },
                { name: "level-down-alt", value: "&#xf3be;  level-down-alt" },
                { name: "level-up-alt", value: "&#xf3bf;  level-up-alt" },
                { name: "life-ring", value: "&#xf1cd;  life-ring" },
                { name: "lightbulb", value: "&#xf0eb;  lightbulb" },
                { name: "link", value: "&#xf0c1;  link" },
                { name: "lira-sign", value: "&#xf195;  lira-sign" },
                { name: "list", value: "&#xf03a;  list" },
                { name: "list-alt", value: "&#xf022;  list-alt" },
                { name: "list-ol", value: "&#xf0cb;  list-ol" },
                { name: "list-ul", value: "&#xf0ca;  list-ul" },
                { name: "location-arrow", value: "&#xf124;  location-arrow" },
                { name: "lock", value: "&#xf023;  lock" },
                { name: "lock-open", value: "&#xf3c1;  lock-open" },
                { name: "long-arrow-alt-down", value: "&#xf309;  long-arrow-alt-down" },
                { name: "long-arrow-alt-left", value: "&#xf30a;  long-arrow-alt-left" },
                { name: "long-arrow-alt-right", value: "&#xf30b;  long-arrow-alt-right" },
                { name: "long-arrow-alt-up", value: "&#xf30c;  long-arrow-alt-up" },
                { name: "low-vision", value: "&#xf2a8;  low-vision" },
                { name: "luggage-cart", value: "&#xf59d;  luggage-cart" },
                { name: "magic", value: "&#xf0d0;  magic" },
                { name: "magnet", value: "&#xf076;  magnet" },
                { name: "mail-bulk", value: "&#xf674;  mail-bulk" },
                { name: "male", value: "&#xf183;  male" },
                { name: "map", value: "&#xf279;  map" },
                { name: "map-marked", value: "&#xf59f;  map-marked" },
                { name: "map-marked-alt", value: "&#xf5a0;  map-marked-alt" },
                { name: "map-marker", value: "&#xf041;  map-marker" },
                { name: "map-marker-alt", value: "&#xf3c5;  map-marker-alt" },
                { name: "map-pin", value: "&#xf276;  map-pin" },
                { name: "map-signs", value: "&#xf277;  map-signs" },
                { name: "marker", value: "&#xf5a1;  marker" },
                { name: "mars", value: "&#xf222;  mars" },
                { name: "mars-double", value: "&#xf227;  mars-double" },
                { name: "mars-stroke", value: "&#xf229;  mars-stroke" },
                { name: "mars-stroke-h", value: "&#xf22b;  mars-stroke-h" },
                { name: "mars-stroke-v", value: "&#xf22a;  mars-stroke-v" },
                { name: "mask", value: "&#xf6fa;  mask" },
                { name: "medal", value: "&#xf5a2;  medal" },
                { name: "medkit", value: "&#xf0fa;  medkit" },
                { name: "meh", value: "&#xf11a;  meh" },
                { name: "meh-blank", value: "&#xf5a4;  meh-blank" },
                { name: "meh-rolling-eyes", value: "&#xf5a5;  meh-rolling-eyes" },
                { name: "memory", value: "&#xf538;  memory" },
                { name: "menorah", value: "&#xf676;  menorah" },
                { name: "mercury", value: "&#xf223;  mercury" },
                { name: "meteor", value: "&#xf753;  meteor" },
                { name: "microchip", value: "&#xf2db;  microchip" },
                { name: "microphone", value: "&#xf130;  microphone" },
                { name: "microphone-alt", value: "&#xf3c9;  microphone-alt" },
                { name: "microphone-alt-slash", value: "&#xf539;  microphone-alt-slash" },
                { name: "microphone-slash", value: "&#xf131;  microphone-slash" },
                { name: "microscope", value: "&#xf610;  microscope" },
                { name: "minus", value: "&#xf068;  minus" },
                { name: "minus-circle", value: "&#xf056;  minus-circle" },
                { name: "minus-square", value: "&#xf146;  minus-square" },
                { name: "mitten", value: "&#xf7b5;  mitten" },
                { name: "mobile", value: "&#xf10b;  mobile" },
                { name: "mobile-alt", value: "&#xf3cd;  mobile-alt" },
                { name: "money-bill", value: "&#xf0d6;  money-bill" },
                { name: "money-bill-alt", value: "&#xf3d1;  money-bill-alt" },
                { name: "money-bill-wave", value: "&#xf53a;  money-bill-wave" },
                { name: "money-bill-wave-alt", value: "&#xf53b;  money-bill-wave-alt" },
                { name: "money-check", value: "&#xf53c;  money-check" },
                { name: "money-check-alt", value: "&#xf53d;  money-check-alt" },
                { name: "monument", value: "&#xf5a6;  monument" },
                { name: "moon", value: "&#xf186;  moon" },
                { name: "mortar-pestle", value: "&#xf5a7;  mortar-pestle" },
                { name: "mosque", value: "&#xf678;  mosque" },
                { name: "motorcycle", value: "&#xf21c;  motorcycle" },
                { name: "mountain", value: "&#xf6fc;  mountain" },
                { name: "mouse", value: "&#xf8cc;  mouse" },
                { name: "mouse-pointer", value: "&#xf245;  mouse-pointer" },
                { name: "mug-hot", value: "&#xf7b6;  mug-hot" },
                { name: "music", value: "&#xf001;  music" },
                { name: "network-wired", value: "&#xf6ff;  network-wired" },
                { name: "neuter", value: "&#xf22c;  neuter" },
                { name: "newspaper", value: "&#xf1ea;  newspaper" },
                { name: "not-equal", value: "&#xf53e;  not-equal" },
                { name: "notes-medical", value: "&#xf481;  notes-medical" },
                { name: "object-group", value: "&#xf247;  object-group" },
                { name: "object-ungroup", value: "&#xf248;  object-ungroup" },
                { name: "oil-can", value: "&#xf613;  oil-can" },
                { name: "om", value: "&#xf679;  om" },
                { name: "otter", value: "&#xf700;  otter" },
                { name: "outdent", value: "&#xf03b;  outdent" },
                { name: "pager", value: "&#xf815;  pager" },
                { name: "paint-brush", value: "&#xf1fc;  paint-brush" },
                { name: "paint-roller", value: "&#xf5aa;  paint-roller" },
                { name: "palette", value: "&#xf53f;  palette" },
                { name: "pallet", value: "&#xf482;  pallet" },
                { name: "paper-plane", value: "&#xf1d8;  paper-plane" },
                { name: "paperclip", value: "&#xf0c6;  paperclip" },
                { name: "parachute-box", value: "&#xf4cd;  parachute-box" },
                { name: "paragraph", value: "&#xf1dd;  paragraph" },
                { name: "parking", value: "&#xf540;  parking" },
                { name: "passport", value: "&#xf5ab;  passport" },
                { name: "pastafarianism", value: "&#xf67b;  pastafarianism" },
                { name: "paste", value: "&#xf0ea;  paste" },
                { name: "pause", value: "&#xf04c;  pause" },
                { name: "pause-circle", value: "&#xf28b;  pause-circle" },
                { name: "paw", value: "&#xf1b0;  paw" },
                { name: "peace", value: "&#xf67c;  peace" },
                { name: "pen", value: "&#xf304;  pen" },
                { name: "pen-alt", value: "&#xf305;  pen-alt" },
                { name: "pen-fancy", value: "&#xf5ac;  pen-fancy" },
                { name: "pen-nib", value: "&#xf5ad;  pen-nib" },
                { name: "pen-square", value: "&#xf14b;  pen-square" },
                { name: "pencil-alt", value: "&#xf303;  pencil-alt" },
                { name: "pencil-ruler", value: "&#xf5ae;  pencil-ruler" },
                { name: "people-carry", value: "&#xf4ce;  people-carry" },
                { name: "pepper-hot", value: "&#xf816;  pepper-hot" },
                { name: "percent", value: "&#xf295;  percent" },
                { name: "percentage", value: "&#xf541;  percentage" },
                { name: "person-booth", value: "&#xf756;  person-booth" },
                { name: "phone", value: "&#xf095;  phone" },
                { name: "phone-alt", value: "&#xf879;  phone-alt" },
                { name: "phone-slash", value: "&#xf3dd;  phone-slash" },
                { name: "phone-square", value: "&#xf098;  phone-square" },
                { name: "phone-square-alt", value: "&#xf87b;  phone-square-alt" },
                { name: "phone-volume", value: "&#xf2a0;  phone-volume" },
                { name: "photo-video", value: "&#xf87c;  photo-video" },
                { name: "piggy-bank", value: "&#xf4d3;  piggy-bank" },
                { name: "pills", value: "&#xf484;  pills" },
                { name: "pizza-slice", value: "&#xf818;  pizza-slice" },
                { name: "place-of-worship", value: "&#xf67f;  place-of-worship" },
                { name: "plane", value: "&#xf072;  plane" },
                { name: "plane-arrival", value: "&#xf5af;  plane-arrival" },
                { name: "plane-departure", value: "&#xf5b0;  plane-departure" },
                { name: "play", value: "&#xf04b;  play" },
                { name: "play-circle", value: "&#xf144;  play-circle" },
                { name: "plug", value: "&#xf1e6;  plug" },
                { name: "plus", value: "&#xf067;  plus" },
                { name: "plus-circle", value: "&#xf055;  plus-circle" },
                { name: "plus-square", value: "&#xf0fe;  plus-square" },
                { name: "podcast", value: "&#xf2ce;  podcast" },
                { name: "poll", value: "&#xf681;  poll" },
                { name: "poll-h", value: "&#xf682;  poll-h" },
                { name: "poo", value: "&#xf2fe;  poo" },
                { name: "poo-storm", value: "&#xf75a;  poo-storm" },
                { name: "poop", value: "&#xf619;  poop" },
                { name: "portrait", value: "&#xf3e0;  portrait" },
                { name: "pound-sign", value: "&#xf154;  pound-sign" },
                { name: "power-off", value: "&#xf011;  power-off" },
                { name: "pray", value: "&#xf683;  pray" },
                { name: "praying-hands", value: "&#xf684;  praying-hands" },
                { name: "prescription", value: "&#xf5b1;  prescription" },
                { name: "prescription-bottle", value: "&#xf485;  prescription-bottle" },
                { name: "prescription-bottle-alt", value: "&#xf486;  prescription-bottle-alt" },
                { name: "print", value: "&#xf02f;  print" },
                { name: "procedures", value: "&#xf487;  procedures" },
                { name: "project-diagram", value: "&#xf542;  project-diagram" },
                { name: "puzzle-piece", value: "&#xf12e;  puzzle-piece" },
                { name: "qrcode", value: "&#xf029;  qrcode" },
                { name: "question", value: "&#xf128;  question" },
                { name: "question-circle", value: "&#xf059;  question-circle" },
                { name: "quidditch", value: "&#xf458;  quidditch" },
                { name: "quote-left", value: "&#xf10d;  quote-left" },
                { name: "quote-right", value: "&#xf10e;  quote-right" },
                { name: "quran", value: "&#xf687;  quran" },
                { name: "radiation", value: "&#xf7b9;  radiation" },
                { name: "radiation-alt", value: "&#xf7ba;  radiation-alt" },
                { name: "rainbow", value: "&#xf75b;  rainbow" },
                { name: "random", value: "&#xf074;  random" },
                { name: "receipt", value: "&#xf543;  receipt" },
                { name: "record-vinyl", value: "&#xf8d9;  record-vinyl" },
                { name: "recycle", value: "&#xf1b8;  recycle" },
                { name: "redo", value: "&#xf01e;  redo" },
                { name: "redo-alt", value: "&#xf2f9;  redo-alt" },
                { name: "registered", value: "&#xf25d;  registered" },
                { name: "remove-format", value: "&#xf87d;  remove-format" },
                { name: "reply", value: "&#xf3e5;  reply" },
                { name: "reply-all", value: "&#xf122;  reply-all" },
                { name: "republican", value: "&#xf75e;  republican" },
                { name: "restroom", value: "&#xf7bd;  restroom" },
                { name: "retweet", value: "&#xf079;  retweet" },
                { name: "ribbon", value: "&#xf4d6;  ribbon" },
                { name: "ring", value: "&#xf70b;  ring" },
                { name: "road", value: "&#xf018;  road" },
                { name: "robot", value: "&#xf544;  robot" },
                { name: "rocket", value: "&#xf135;  rocket" },
                { name: "route", value: "&#xf4d7;  route" },
                { name: "rss", value: "&#xf09e;  rss" },
                { name: "rss-square", value: "&#xf143;  rss-square" },
                { name: "ruble-sign", value: "&#xf158;  ruble-sign" },
                { name: "ruler", value: "&#xf545;  ruler" },
                { name: "ruler-combined", value: "&#xf546;  ruler-combined" },
                { name: "ruler-horizontal", value: "&#xf547;  ruler-horizontal" },
                { name: "ruler-vertical", value: "&#xf548;  ruler-vertical" },
                { name: "running", value: "&#xf70c;  running" },
                { name: "rupee-sign", value: "&#xf156;  rupee-sign" },
                { name: "sad-cry", value: "&#xf5b3;  sad-cry" },
                { name: "sad-tear", value: "&#xf5b4;  sad-tear" },
                { name: "satellite", value: "&#xf7bf;  satellite" },
                { name: "satellite-dish", value: "&#xf7c0;  satellite-dish" },
                { name: "save", value: "&#xf0c7;  save" },
                { name: "school", value: "&#xf549;  school" },
                { name: "screwdriver", value: "&#xf54a;  screwdriver" },
                { name: "scroll", value: "&#xf70e;  scroll" },
                { name: "sd-card", value: "&#xf7c2;  sd-card" },
                { name: "search", value: "&#xf002;  search" },
                { name: "search-dollar", value: "&#xf688;  search-dollar" },
                { name: "search-location", value: "&#xf689;  search-location" },
                { name: "search-minus", value: "&#xf010;  search-minus" },
                { name: "search-plus", value: "&#xf00e;  search-plus" },
                { name: "seedling", value: "&#xf4d8;  seedling" },
                { name: "server", value: "&#xf233;  server" },
                { name: "shapes", value: "&#xf61f;  shapes" },
                { name: "share", value: "&#xf064;  share" },
                { name: "share-alt", value: "&#xf1e0;  share-alt" },
                { name: "share-alt-square", value: "&#xf1e1;  share-alt-square" },
                { name: "share-square", value: "&#xf14d;  share-square" },
                { name: "shekel-sign", value: "&#xf20b;  shekel-sign" },
                { name: "shield-alt", value: "&#xf3ed;  shield-alt" },
                { name: "ship", value: "&#xf21a;  ship" },
                { name: "shipping-fast", value: "&#xf48b;  shipping-fast" },
                { name: "shoe-prints", value: "&#xf54b;  shoe-prints" },
                { name: "shopping-bag", value: "&#xf290;  shopping-bag" },
                { name: "shopping-basket", value: "&#xf291;  shopping-basket" },
                { name: "shopping-cart", value: "&#xf07a;  shopping-cart" },
                { name: "shower", value: "&#xf2cc;  shower" },
                { name: "shuttle-van", value: "&#xf5b6;  shuttle-van" },
                { name: "sign", value: "&#xf4d9;  sign" },
                { name: "sign-in-alt", value: "&#xf2f6;  sign-in-alt" },
                { name: "sign-language", value: "&#xf2a7;  sign-language" },
                { name: "sign-out-alt", value: "&#xf2f5;  sign-out-alt" },
                { name: "signal", value: "&#xf012;  signal" },
                { name: "signature", value: "&#xf5b7;  signature" },
                { name: "sim-card", value: "&#xf7c4;  sim-card" },
                { name: "sitemap", value: "&#xf0e8;  sitemap" },
                { name: "skating", value: "&#xf7c5;  skating" },
                { name: "skiing", value: "&#xf7c9;  skiing" },
                { name: "skiing-nordic", value: "&#xf7ca;  skiing-nordic" },
                { name: "skull", value: "&#xf54c;  skull" },
                { name: "skull-crossbones", value: "&#xf714;  skull-crossbones" },
                { name: "slash", value: "&#xf715;  slash" },
                { name: "sleigh", value: "&#xf7cc;  sleigh" },
                { name: "sliders-h", value: "&#xf1de;  sliders-h" },
                { name: "smile", value: "&#xf118;  smile" },
                { name: "smile-beam", value: "&#xf5b8;  smile-beam" },
                { name: "smile-wink", value: "&#xf4da;  smile-wink" },
                { name: "smog", value: "&#xf75f;  smog" },
                { name: "smoking", value: "&#xf48d;  smoking" },
                { name: "smoking-ban", value: "&#xf54d;  smoking-ban" },
                { name: "sms", value: "&#xf7cd;  sms" },
                { name: "snowboarding", value: "&#xf7ce;  snowboarding" },
                { name: "snowflake", value: "&#xf2dc;  snowflake" },
                { name: "snowman", value: "&#xf7d0;  snowman" },
                { name: "snowplow", value: "&#xf7d2;  snowplow" },
                { name: "socks", value: "&#xf696;  socks" },
                { name: "solar-panel", value: "&#xf5ba;  solar-panel" },
                { name: "sort", value: "&#xf0dc;  sort" },
                { name: "sort-alpha-down", value: "&#xf15d;  sort-alpha-down" },
                { name: "sort-alpha-down-alt", value: "&#xf881;  sort-alpha-down-alt" },
                { name: "sort-alpha-up", value: "&#xf15e;  sort-alpha-up" },
                { name: "sort-alpha-up-alt", value: "&#xf882;  sort-alpha-up-alt" },
                { name: "sort-amount-down", value: "&#xf160;  sort-amount-down" },
                { name: "sort-amount-down-alt", value: "&#xf884;  sort-amount-down-alt" },
                { name: "sort-amount-up", value: "&#xf161;  sort-amount-up" },
                { name: "sort-amount-up-alt", value: "&#xf885;  sort-amount-up-alt" },
                { name: "sort-down", value: "&#xf0dd;  sort-down" },
                { name: "sort-numeric-down", value: "&#xf162;  sort-numeric-down" },
                { name: "sort-numeric-down-alt", value: "&#xf886;  sort-numeric-down-alt" },
                { name: "sort-numeric-up", value: "&#xf163;  sort-numeric-up" },
                { name: "sort-numeric-up-alt", value: "&#xf887;  sort-numeric-up-alt" },
                { name: "sort-up", value: "&#xf0de;  sort-up" },
                { name: "spa", value: "&#xf5bb;  spa" },
                { name: "space-shuttle", value: "&#xf197;  space-shuttle" },
                { name: "spell-check", value: "&#xf891;  spell-check" },
                { name: "spider", value: "&#xf717;  spider" },
                { name: "spinner", value: "&#xf110;  spinner" },
                { name: "splotch", value: "&#xf5bc;  splotch" },
                { name: "spray-can", value: "&#xf5bd;  spray-can" },
                { name: "square", value: "&#xf0c8;  square" },
                { name: "square-full", value: "&#xf45c;  square-full" },
                { name: "square-root-alt", value: "&#xf698;  square-root-alt" },
                { name: "stamp", value: "&#xf5bf;  stamp" },
                { name: "star", value: "&#xf005;  star" },
                { name: "star-and-crescent", value: "&#xf699;  star-and-crescent" },
                { name: "star-half", value: "&#xf089;  star-half" },
                { name: "star-half-alt", value: "&#xf5c0;  star-half-alt" },
                { name: "star-of-david", value: "&#xf69a;  star-of-david" },
                { name: "star-of-life", value: "&#xf621;  star-of-life" },
                { name: "step-backward", value: "&#xf048;  step-backward" },
                { name: "step-forward", value: "&#xf051;  step-forward" },
                { name: "stethoscope", value: "&#xf0f1;  stethoscope" },
                { name: "sticky-note", value: "&#xf249;  sticky-note" },
                { name: "stop", value: "&#xf04d;  stop" },
                { name: "stop-circle", value: "&#xf28d;  stop-circle" },
                { name: "stopwatch", value: "&#xf2f2;  stopwatch" },
                { name: "store", value: "&#xf54e;  store" },
                { name: "store-alt", value: "&#xf54f;  store-alt" },
                { name: "stream", value: "&#xf550;  stream" },
                { name: "street-view", value: "&#xf21d;  street-view" },
                { name: "strikethrough", value: "&#xf0cc;  strikethrough" },
                { name: "stroopwafel", value: "&#xf551;  stroopwafel" },
                { name: "subscript", value: "&#xf12c;  subscript" },
                { name: "subway", value: "&#xf239;  subway" },
                { name: "suitcase", value: "&#xf0f2;  suitcase" },
                { name: "suitcase-rolling", value: "&#xf5c1;  suitcase-rolling" },
                { name: "sun", value: "&#xf185;  sun" },
                { name: "superscript", value: "&#xf12b;  superscript" },
                { name: "surprise", value: "&#xf5c2;  surprise" },
                { name: "swatchbook", value: "&#xf5c3;  swatchbook" },
                { name: "swimmer", value: "&#xf5c4;  swimmer" },
                { name: "swimming-pool", value: "&#xf5c5;  swimming-pool" },
                { name: "synagogue", value: "&#xf69b;  synagogue" },
                { name: "sync", value: "&#xf021;  sync" },
                { name: "sync-alt", value: "&#xf2f1;  sync-alt" },
                { name: "syringe", value: "&#xf48e;  syringe" },
                { name: "table", value: "&#xf0ce;  table" },
                { name: "table-tennis", value: "&#xf45d;  table-tennis" },
                { name: "tablet", value: "&#xf10a;  tablet" },
                { name: "tablet-alt", value: "&#xf3fa;  tablet-alt" },
                { name: "tablets", value: "&#xf490;  tablets" },
                { name: "tachometer-alt", value: "&#xf3fd;  tachometer-alt" },
                { name: "tag", value: "&#xf02b;  tag" },
                { name: "tags", value: "&#xf02c;  tags" },
                { name: "tape", value: "&#xf4db;  tape" },
                { name: "tasks", value: "&#xf0ae;  tasks" },
                { name: "taxi", value: "&#xf1ba;  taxi" },
                { name: "teeth", value: "&#xf62e;  teeth" },
                { name: "teeth-open", value: "&#xf62f;  teeth-open" },
                { name: "temperature-high", value: "&#xf769;  temperature-high" },
                { name: "temperature-low", value: "&#xf76b;  temperature-low" },
                { name: "tenge", value: "&#xf7d7;  tenge" },
                { name: "terminal", value: "&#xf120;  terminal" },
                { name: "text-height", value: "&#xf034;  text-height" },
                { name: "text-width", value: "&#xf035;  text-width" },
                { name: "th", value: "&#xf00a;  th" },
                { name: "th-large", value: "&#xf009;  th-large" },
                { name: "th-list", value: "&#xf00b;  th-list" },
                { name: "theater-masks", value: "&#xf630;  theater-masks" },
                { name: "thermometer", value: "&#xf491;  thermometer" },
                { name: "thermometer-empty", value: "&#xf2cb;  thermometer-empty" },
                { name: "thermometer-full", value: "&#xf2c7;  thermometer-full" },
                { name: "thermometer-half", value: "&#xf2c9;  thermometer-half" },
                { name: "thermometer-quarter", value: "&#xf2ca;  thermometer-quarter" },
                { name: "thermometer-three-quarters", value: "&#xf2c8;  thermometer-three-quarters" },
                { name: "thumbs-down", value: "&#xf165;  thumbs-down" },
                { name: "thumbs-up", value: "&#xf164;  thumbs-up" },
                { name: "thumbtack", value: "&#xf08d;  thumbtack" },
                { name: "ticket-alt", value: "&#xf3ff;  ticket-alt" },
                { name: "times", value: "&#xf00d;  times" },
                { name: "times-circle", value: "&#xf057;  times-circle" },
                { name: "tint", value: "&#xf043;  tint" },
                { name: "tint-slash", value: "&#xf5c7;  tint-slash" },
                { name: "tired", value: "&#xf5c8;  tired" },
                { name: "toggle-off", value: "&#xf204;  toggle-off" },
                { name: "toggle-on", value: "&#xf205;  toggle-on" },
                { name: "toilet", value: "&#xf7d8;  toilet" },
                { name: "toilet-paper", value: "&#xf71e;  toilet-paper" },
                { name: "toolbox", value: "&#xf552;  toolbox" },
                { name: "tools", value: "&#xf7d9;  tools" },
                { name: "tooth", value: "&#xf5c9;  tooth" },
                { name: "torah", value: "&#xf6a0;  torah" },
                { name: "torii-gate", value: "&#xf6a1;  torii-gate" },
                { name: "tractor", value: "&#xf722;  tractor" },
                { name: "trademark", value: "&#xf25c;  trademark" },
                { name: "traffic-light", value: "&#xf637;  traffic-light" },
                { name: "train", value: "&#xf238;  train" },
                { name: "tram", value: "&#xf7da;  tram" },
                { name: "transgender", value: "&#xf224;  transgender" },
                { name: "transgender-alt", value: "&#xf225;  transgender-alt" },
                { name: "trash", value: "&#xf1f8;  trash" },
                { name: "trash-alt", value: "&#xf2ed;  trash-alt" },
                { name: "trash-restore", value: "&#xf829;  trash-restore" },
                { name: "trash-restore-alt", value: "&#xf82a;  trash-restore-alt" },
                { name: "tree", value: "&#xf1bb;  tree" },
                { name: "trophy", value: "&#xf091;  trophy" },
                { name: "truck", value: "&#xf0d1;  truck" },
                { name: "truck-loading", value: "&#xf4de;  truck-loading" },
                { name: "truck-monster", value: "&#xf63b;  truck-monster" },
                { name: "truck-moving", value: "&#xf4df;  truck-moving" },
                { name: "truck-pickup", value: "&#xf63c;  truck-pickup" },
                { name: "tshirt", value: "&#xf553;  tshirt" },
                { name: "tty", value: "&#xf1e4;  tty" },
                { name: "tv", value: "&#xf26c;  tv" },
                { name: "umbrella", value: "&#xf0e9;  umbrella" },
                { name: "umbrella-beach", value: "&#xf5ca;  umbrella-beach" },
                { name: "underline", value: "&#xf0cd;  underline" },
                { name: "undo", value: "&#xf0e2;  undo" },
                { name: "undo-alt", value: "&#xf2ea;  undo-alt" },
                { name: "universal-access", value: "&#xf29a;  universal-access" },
                { name: "university", value: "&#xf19c;  university" },
                { name: "unlink", value: "&#xf127;  unlink" },
                { name: "unlock", value: "&#xf09c;  unlock" },
                { name: "unlock-alt", value: "&#xf13e;  unlock-alt" },
                { name: "upload", value: "&#xf093;  upload" },
                { name: "user", value: "&#xf007;  user" },
                { name: "user-alt", value: "&#xf406;  user-alt" },
                { name: "user-alt-slash", value: "&#xf4fa;  user-alt-slash" },
                { name: "user-astronaut", value: "&#xf4fb;  user-astronaut" },
                { name: "user-check", value: "&#xf4fc;  user-check" },
                { name: "user-circle", value: "&#xf2bd;  user-circle" },
                { name: "user-clock", value: "&#xf4fd;  user-clock" },
                { name: "user-cog", value: "&#xf4fe;  user-cog" },
                { name: "user-edit", value: "&#xf4ff;  user-edit" },
                { name: "user-friends", value: "&#xf500;  user-friends" },
                { name: "user-graduate", value: "&#xf501;  user-graduate" },
                { name: "user-injured", value: "&#xf728;  user-injured" },
                { name: "user-lock", value: "&#xf502;  user-lock" },
                { name: "user-md", value: "&#xf0f0;  user-md" },
                { name: "user-minus", value: "&#xf503;  user-minus" },
                { name: "user-ninja", value: "&#xf504;  user-ninja" },
                { name: "user-nurse", value: "&#xf82f;  user-nurse" },
                { name: "user-plus", value: "&#xf234;  user-plus" },
                { name: "user-secret", value: "&#xf21b;  user-secret" },
                { name: "user-shield", value: "&#xf505;  user-shield" },
                { name: "user-slash", value: "&#xf506;  user-slash" },
                { name: "user-tag", value: "&#xf507;  user-tag" },
                { name: "user-tie", value: "&#xf508;  user-tie" },
                { name: "user-times", value: "&#xf235;  user-times" },
                { name: "users", value: "&#xf0c0;  users" },
                { name: "users-cog", value: "&#xf509;  users-cog" },
                { name: "utensil-spoon", value: "&#xf2e5;  utensil-spoon" },
                { name: "utensils", value: "&#xf2e7;  utensils" },
                { name: "vector-square", value: "&#xf5cb;  vector-square" },
                { name: "venus", value: "&#xf221;  venus" },
                { name: "venus-double", value: "&#xf226;  venus-double" },
                { name: "venus-mars", value: "&#xf228;  venus-mars" },
                { name: "vial", value: "&#xf492;  vial" },
                { name: "vials", value: "&#xf493;  vials" },
                { name: "video", value: "&#xf03d;  video" },
                { name: "video-slash", value: "&#xf4e2;  video-slash" },
                { name: "vihara", value: "&#xf6a7;  vihara" },
                { name: "voicemail", value: "&#xf897;  voicemail" },
                { name: "volleyball-ball", value: "&#xf45f;  volleyball-ball" },
                { name: "volume-down", value: "&#xf027;  volume-down" },
                { name: "volume-mute", value: "&#xf6a9;  volume-mute" },
                { name: "volume-off", value: "&#xf026;  volume-off" },
                { name: "volume-up", value: "&#xf028;  volume-up" },
                { name: "vote-yea", value: "&#xf772;  vote-yea" },
                { name: "vr-cardboard", value: "&#xf729;  vr-cardboard" },
                { name: "walking", value: "&#xf554;  walking" },
                { name: "wallet", value: "&#xf555;  wallet" },
                { name: "warehouse", value: "&#xf494;  warehouse" },
                { name: "water", value: "&#xf773;  water" },
                { name: "wave-square", value: "&#xf83e;  wave-square" },
                { name: "weight", value: "&#xf496;  weight" },
                { name: "weight-hanging", value: "&#xf5cd;  weight-hanging" },
                { name: "wheelchair", value: "&#xf193;  wheelchair" },
                { name: "wifi", value: "&#xf1eb;  wifi" },
                { name: "wind", value: "&#xf72e;  wind" },
                { name: "window-close", value: "&#xf410;  window-close" },
                { name: "window-maximize", value: "&#xf2d0;  window-maximize" },
                { name: "window-minimize", value: "&#xf2d1;  window-minimize" },
                { name: "window-restore", value: "&#xf2d2;  window-restore" },
                { name: "wine-bottle", value: "&#xf72f;  wine-bottle" },
                { name: "wine-glass", value: "&#xf4e3;  wine-glass" },
                { name: "wine-glass-alt", value: "&#xf5ce;  wine-glass-alt" },
                { name: "won-sign", value: "&#xf159;  won-sign" },
                { name: "wrench", value: "&#xf0ad;  wrench" },
                { name: "x-ray", value: "&#xf497;  x-ray" },
                { name: "yen-sign", value: "&#xf157;  yen-sign" },
                { name: "yin-yang", value: "&#xf6ad;  yin-yang" }
            ]);
        }
    });
};